### ISSUE TITLE
[Bug]  Can't download artist or album covers

### ISSUE THREAD

**Issue by branja6** [sailfishos-applications/flowplayer#30]
**SailfishOS VERSION** (Settings → About product → Build): 4.5.0.24
<br />**HARDWARE** (Settings → About product → Manufacturer & Product name): Xperia 10 III
<br />**FlowPlayer VERSION** (FlowPlayer → [Top pulley] Settings → [Top pulley] About): 0.1-9
<br />

#### BUG DESCRIPTION
Album and artist images are not being downloaded.

#### STEPS TO REPRODUCE
The download seems to start but nothing gets downloaded.

#### ADDITIONAL INFORMATION

It seems like it started working the first time I opened the app and tried it, but no images were saved. Every other time, it just displays 'not found' next to the album image. Artist images seem to be found, but they can't be displayed.
![Screenshot_20231206_003](https://github.com/sailfishos-applications/flowplayer/assets/71647226/a37beddb-5532-4e73-a345-1be4edfae122)
![Screenshot_20231206_002](https://github.com/sailfishos-applications/flowplayer/assets/71647226/a72346ff-9476-4830-a676-9fb4c2719883)

**Comment by Olf0** [comment]
Something seems to go awry with FlowPlayer's database handling.
This may be due to [the recent changes to its path](https://github.com/sailfishos-applications/flowplayer/pull/21#issuecomment-1842332321) by @dcaliste, while eliminating hardcoded paths and making FlowPlayer's paths adhering to Jolla's current specifications for SailfishOS.

P.S.: Really nice and broad selection of music you are listening to, AFAICS I do like all of them (except for Bryan Adams!). :smiley:

**Comment by eson57** [comment]
Same problem here. "Not found" on all my tracks, so I was wondering why Flowplayer do not check meta data for album art? All my songs have it, working fine in Unplayer,
